module.exports = {
  invalid_array: (arr) => new TypeError(`Invalid array, expected an array but received ${arr}.`),
  invalid_image_path: (path) => new Error(`${path} is not a valid image.`),
  unknown_image: (path) => new Error(`${path} is an unknown image type.`),
  size_incompatible: (rw, rh, ew, eh) => new RangeError(`Size incompatible, expected ${ew} and ${eh} but received ${rw} and ${rh}.`),
  expect_nonnegative: (number) => new RangeError(`${number} is not a non-negative integer.`),
  expect_positive: (number) => new RangeError(`${number} is not a positive number.`),
  overflow: (index, max) => new RangeError(`${index} overflow, expected not larger than ${max}.`),
  invalid_channel_size: (size) => new RangeError(`Invalid channels number, expected at most 4 channels but received ${size}.`),
  invalid_channel_index: (index) => new Error(`Invalid channel index, expected 0, 1, 2, 3 but received ${index}`),
  invalid_filter_size: (size) => new RangeError(`Invalid filter size, expected a positive odd number but received ${size}`),
  invalid_filter_shape: (row, col) => new RangeError(`Invalid filter size, expected a square matrix but received ${row} and ${col}.`),
  invalid_1D_filter: (filter) => new TypeError(`Invalid 1D filter, expected an 1D array with numbers but received ${filter}`),
  invalid_2D_filter: (filter) => new TypeError(`Invalid 2D filter, expected an 2D array with numbers but received ${filter}`),
  invalid_point: (point) => new TypeError(`Expected an array with size 2, but received ${point}.`),
  invalid_rotation: (rotation) => new RangeError(`${rotation} is not a valid rotation. -3, -2, -1, 1, 2, 3 are expected.`),
  invalid_direction: (direction) => new TypeError(`Invalid direction, expected x or y but received ${direction}.`),

  INVALID_IMAGE: new TypeError('Received invalid image.'),
  INVALID_RGB: new TypeError('Expect RGB image.'),
}
